src/objects/Account_Card__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Cards</relationshipLabel>
        <relationshipName>Account_Cards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Card_Id</label>
        <referenceTo>Card__c</referenceTo>
        <relationshipLabel>Account Cards</relationshipLabel>
        <relationshipName>Account_Cards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Card</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Account Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Card__c.object
<CustomObject>
    <fields>
        <fullName>CardNumber__c</fullName>
        <label>CardNumber</label>
        <length>16</length>
        <maskChar>X</maskChar>
        <maskType>creditCard</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <fields>
        <fullName>Cash__c</fullName>
        <label>Cash</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PaymentforgoodsController.cls
/**
 * Created by Pavel on 09.09.2019.
 */

public with sharing class PaymentforgoodsController {
    @AuraEnabled
    public static List <Account_Card__c> getCards(String accId) {
        return [SELECT Card_Id__c,Card_Id__r.Name,Card_Id__r.CardNumber__c,Card_Id__r.Cash__c
                    FROM Account_Card__c
                        WHERE AccountId__c =: accId];
    }
    @AuraEnabled
    public static void delCard(Id cardId){
        delete [SELECT Id,(
                    SELECT id
                    FROM Account_Cards__r
                        WHERE Card_Id__c =: cardId)
                FROM Card__c
                    WHERE Id =: cardId];
    }
    @AuraEnabled
    public static void payOrder(String cardId,Integer totalCost){
        System.debug('cardId: ' + cardId);
        System.debug('totalCost: ' + totalCost);
        Card__c card = [SELECT Cash__c FROM Card__c WHERE Id =: cardId];
        System.debug('card: ' + card);
        if(card.Cash__c >= totalCost){
            card.Cash__c -= totalCost;
            update card;
        }

    }
}