src/objects/Account_Card__c.object
<CustomObject>
    <fields>
        <fullName>AccountId__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>AccountId</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Cards</relationshipLabel>
        <relationshipName>Account_Cards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Card_Id__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Card_Id</label>
        <referenceTo>Card__c</referenceTo>
        <relationshipLabel>Account Cards</relationshipLabel>
        <relationshipName>Account_Cards</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <label>Account Card</label>
    <nameField>
        <displayFormat>OF-{0000}</displayFormat>
        <label>Account Card Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Card__c.object
<CustomObject>
    <label>Card</label>
    <nameField>
        <label>Card Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Cards</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewCardController.cls
/**
 * Created by Pavel on 11.09.2019.
 */

public with sharing class NewCardController {
    @AuraEnabled
    public static void saveCard(String card,String accId) {
        try {
            insert (Card__c)JSON.deserialize(card, Card__c.class);
            //Card__c cardd = (Card__c)JSON.deserialize(card, Card__c.class);
            Account_Card__c cardd = [SELECT Card_Id__c
                                FROM Account_Card__c
                                WHERE AccountId__c =: accId];
            System.debug('The value is: ' + accId);
            System.debug('The value is: ' + cardd);
            Account_Card__c newAccountCard = new Account_Card__c(Card_Id__c = cardd.Card_Id__c,AccountId__c = accId);
            System.debug('The value is: ' + newAccountCard);
            //System.debug('The value is: ' + cardd[0].Card_Id__c);
            insert newAccountCard;
        }
        catch(DMLException e){
            throw new AuraHandledException(e.getDMLMessage(0));
        }catch(Exception e){
            throw new AuraHandledException(e.getMessage());
        }

}
}