src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Login__c</fullName>
        <caseSensitive>true</caseSensitive>
        <label>Login</label>
        <required>true</required>
        <type>Email</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>20</length>
        <maskChar>asterisk</maskChar>
        <maskType>all</maskType>
        <required>true</required>
        <type>EncryptedText</type>
    </fields>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/RegisterController.cls
public class RegisterController {
    public Account account {get; set;}
    public RegisterController(){
        account = new Account();
        addAccount();
    }
    public String addAccount(){
       Account accountNew = new Account(
           Name = account.Name,
           Phone = account.Phone,
           Login__c = account.Login__c,
           Password__c = account.Password__c
        );
        insert accountNew;
        return accountNew.Id;
      }
}