src/objects/Catalog__c.object
<CustomObject>
    <fields>
        <fullName>Category__c</fullName>
        <label>Category</label>
        <required>true</required>
        <type>MultiselectPicklist</type>
        <valueSet>
            <restricted>true</restricted>
            <valueSetDefinition>
                <value>
                    <fullName>Products</fullName>
                </value>
                <value>
                    <fullName>Household chemicals</fullName>
                </value>
                <value>
                    <fullName>Entertainment</fullName>
                </value>
                <value>
                    <fullName>18+</fullName>
                </value>
            </valueSetDefinition>
        </valueSet>
    </fields>
    <fields>
        <fullName>Cost__c</fullName>
        <label>Cost</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Catalog</label>
    <nameField>
        <label>Item Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Catalogs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/EditOrderController.cls
/**
 * Created by user on 09-Sep-19.
 */

public with sharing class EditOrderController {

    @AuraEnabled
    public static Account getAccountById(String AccId) {
        return [SELECT Id, Name, Phone FROM Account WHERE Id =: AccId];
    }

    @AuraEnabled
    public static Account saveAccount(Account acc) {
        update acc;
        return acc;
    }

    @AuraEnabled
    public static List<Catalog__c> getListOfProducts() {
        return [SELECT Id, Name, Quantity__c, Category__c, Cost__c FROM Catalog__c];
    }
}